### ISSUE TITLE
How do i detect fragment size automatically?

### ISSUE THREAD

**Issue by tseemann** [hsinnan75/MapCaller#10]
```
-size Sequencing fragment size [default: 500, 
MapCaller can predict the fragment size automatically]
```

Default is 500 but i want to use auto-detection. How?

**Comment by hsinnan75** [comment]
If the fragment size of the sequencing library is known, you may use the option "-size" to indicate the fragment size. Otherwise, MapCaller will predict the fragment size according to the paired alignments, but it needs at least 1000 paired alignments to infer the fragment size.

**Comment by tseemann** [comment]
It says the default is `-size 500`.  So that means it is choosing 500 for me.  How do I disable that so it does automatic `-size` ?

**Comment by hsinnan75** [comment]
The default size is only used for the initial fragment size for selecting paired alignments when there are multiple pairs. Thus the fragment size will be refined periodically during read mapping. The default size or designated size given by the user work the same way. In fact, it does not matter what the value is given. MapCaller will always infer the average fragment size during the read mapping.

**Comment by tseemann** [comment]
Ok. Thank you for making that clear.
