### ISSUE TITLE
Only need to compile libhts.a

### ISSUE THREAD

**Issue by tseemann** [hsinnan75/MapCaller#17]
Because you only use the static htslib library, you don't need to compile the dynamic .so ones. This makes it quicker to compile the `makefile`:

OLD:
```
htslib:
                $(MAKE) -C src/htslib
```

NEW:
```
htslib:
                $(MAKE) -C src/htslib libhts.a
```

**Comment by hsinnan75** [comment]
Thanks. The makefile is updated.
