### ISSUE TITLE
What is SVsim.cpp in main folder?

### ISSUE THREAD

**Issue by tseemann** [hsinnan75/MapCaller#18]
`SVsim.cpp` is in the top folder - what is it?

**Comment by hsinnan75** [comment]
This file is used to simulate sequence variations for a given genome. It outputs a mutant genome with simulated SNVs, indels, inversions and translocations as well as a VCF file. It is not a part of MapCaller. I just used this program to generate synthetic genomes. Then I used the program WGSIM to generate short reads with the mutant genomes.

**Comment by tseemann** [comment]
Maybe you should move it to `src/SVsim` then?

**Comment by hsinnan75** [comment]
Thank you for the suggestion. I've moved it to src/sv_simulator/.
