### ISSUE TITLE
Support for ploidy != 2

### ISSUE THREAD

**Issue by tseemann** [hsinnan75/MapCaller#22]
Genotypes seem to be called as diploid n=2.
Is MapCaller a naive frequency caller or does it have a statistica model?
I was wondering if you would support different ploidy?
I am interested in n=1 (haploid, bacteria).
Or should I just filter the VCF ?

**Comment by hsinnan75** [comment]
Basically, MapCaller is based on allele frequency to call variants. It supports haploid and diploid. I think it should be able to support different ploidy. I'll try with some synthetic data sets.

**Comment by hsinnan75** [comment]
I added a new argument (-ploidy) for specifying the number of complete sets of chromosomes in a cell. If your sample is monoploid, you may use run MapCaller with "-ploidy 1". Please let me know if you find any problems on running MapCaller. Thank you!

**Comment by tseemann** [comment]
Could you please tag a release for it?

`git tag v0.9.9.8 && git push --tags`

**Comment by hsinnan75** [comment]
Sure, the current version is v0.9.9.9. There is one more step for v1.0.0.0 which will include CNV detection.

**Comment by tseemann** [comment]
New related bug #30
