### ISSUE TITLE
-ploidy 1 still has diploid genotypes

### ISSUE THREAD

**Issue by tseemann** [hsinnan75/MapCaller#30]
When I use `-ploidy 1` I would expect `GT=0` or `GT=1` only, but I get `GT=1|1`

`PASS    DP=18;AD=18;DUP=0;AF=1.000;GT=1|1;TYPE=SUBSTITUTE`

**Comment by hsinnan75** [comment]
Hi, I made a mistake on labeling genotypes. I'd like to know what the genotype label will be in such case (GT=0 or GT=1). Thank you!

**Comment by tseemann** [comment]
and for `-ploidy 4` you would have `GT=1|1|1|1` etc. (i think)

**Comment by hsinnan75** [comment]
Thank you! I've updated MapCaller (v0.9.9.15) to fix the wrong annotation. However, MapCaller supports monoploid and diploid for now. I have to survey how to deal with annotation for triploid and more.

**Comment by tseemann** [comment]
Thank you.
