### ISSUE TITLE
vcf convert plink format

### ISSUE THREAD

**Issue by feng0377** [hsinnan75/MapCaller#41]
The  vcf file produced by MapCaller  can't be converted into Plink formate file (map and ped), command: vcftools --vcf result.vcf  --plink --out plink,  Error: Require Genotypes in VCF file in order to output as PLINK. However, the problem don't happen in GATK software.   The example  vcf  in  MapCaller tutorial (ref.vcf and out.vcf) can't work too.
      Eagerly looking forward to response, thanks very much again！

**Comment by hsinnan75** [comment]
Hi, thanks for the information. MapCaller does output genotype for snv and indels. I think it is an issue of formatting the attribute fields. I'll work on it and figure out how to modify the output. Thank you again.

**Comment by feng0377** [comment]
Hi, hsinnan75, thank you very much. Looking forward to good news!

**Comment by hsinnan75** [comment]
Hi, I've fixed the problem. Please download the latest version (v0.9.9.23). Please try again and let me know if there are any other problems regarding the use of MapCaller. Thank you!!

**Comment by feng0377** [comment]
I am glad to receive your messenge，and I'm using it as soon as possible. Thank you  again!
