### ISSUE TITLE
Incorrect definition of VCF header

### ISSUE THREAD

**Issue by motthy** [hsinnan75/MapCaller#43]
Hi, hsinnan75,

I used MapCaller 0.9.9.23. Running bcftools, this error message showed.
`[W::vcf_parse] INFO 'NTFREQ' is not defined in the header, assuming Type=String`

I think that you need to change the VCF header,
`##FORMAT=<ID=NTFREQ,Number=4,Type=Integer,Description="base depth">`
to 
`##INFO=<ID=NTFREQ,Number=4,Type=Integer,Description="base depth">`

Thank you.

**Comment by hsinnan75** [comment]
Thank you, motthy. I've fixed the problem and updated MapCaller. Thank you!!

**Comment by motthy** [comment]
Thank you for your quick response!!
