### ISSUE TITLE
add summary option

### ISSUE THREAD

**Issue by fei0810** [hsinnan75/MapCaller#44]
Hi ,

I have tested MapCaller, it is cool. Could you add a summary option such as `--summary-file` so that user can read alignment summary in a file.  I want to use MapCaller in my own pipeline, so i can check the summary file anytime.
I try use `> mapcaller.log 2>&1`, but the log file would save something like below
```
^M0 paired-end reads have been processed in 0 seconds...
```
What user really need are: 

```
All the 3065444296 paired-end reads have been processed in 44220 seconds.
  2796573021 ( 91.22%) reads are mapped properly.
  2496133858 ( 81.42%) reads are mapped in pairs.
        Estimated AvgCoverage = 88
        Duplication rate=69.41%
        Estimated fragment size = 333, insert size = 33
Identify all variants (min_alt_allele_depth=5)...
        Write all the predicted sample variations to file [4sample_mapcaller_raw.vcf]...
        34635289(snp); 1497902(ins); 1344402(del); 6008(trans); 269(inversion)
variant calling has been done in 264 seconds.
All done! It took 44751 seconds to complete the data analysis.
```

Thankyou!

**Comment by hsinnan75** [comment]
Hello, I've updated MapCaller with logging the summary report. Please update your MapCaller. The argument is "-log job.log", default filename is "job.log". Thank you!

**Comment by fei0810** [comment]
@hsinnan75 Thank you ! I will try it tomorrow.

**Comment by fei0810** [comment]
> Hello, I've updated MapCaller with logging the summary report. Please update your MapCaller. The argument is "-log job.log", default filename is "job.log". Thank you!

Hi, the log file is work well now.
