### ISSUE TITLE
Typos in information field and header 

### ISSUE THREAD

**Issue by qhelleu** [hsinnan75/MapCaller#45]
Hi,

Three lines in the info field are open with a bracket but not closed. It looks like vcf-merge doesn't like that!
##INFO=<ID=END,Number=1,Type=Integer,Description="Last position(inclusive) of the reported block"
##FILTER=<ID=DUP,Description="Duplicated regions(>=50bp)."
##FILTER=<ID=Gaps,Description="Region without any read alignment(>=50bp)."

Also in the header the sample is indicated as 'unkonwn' instead of 'unknown'. Alternatively it would be nice to have an option to indicate the sample name directly to MapCaller.

Thanks,
Best.

**Comment by hsinnan75** [comment]
Hi, thanks for the information. I've fixed the typos and updated MapCaller to v0.9.9.25. Thank you very much!

**Comment by tseemann** [comment]
@qhelleu can you close this issue now?  brew has been upgraded.
