### ISSUE TITLE
Put bwt_index into MapCaller -idx ?

### ISSUE THREAD

**Issue by tseemann** [hsinnan75/MapCaller#47]
I think it would be good to have the reference index inside `MapCaller` like `minimap2` does. 
eg.
```
% Mapcaller -index reference.fasta prefix
```

**Comment by hsinnan75** [comment]
It sounds like a great idea. I'll try to make it happen.

**Comment by hsinnan75** [comment]
Hi, I've updated MapCaller to v0.9.9.27. Now MapCaller can build a reference index via 
% MapCaller index ref.fa prefix

**Comment by tseemann** [comment]
Oh, that's great !
