### ISSUE TITLE
Automatic index of a FASTA file reference

### ISSUE THREAD

**Issue by tseemann** [hsinnan75/MapCaller#48]
For bacterial genomes it is very fast to bwt_index and we do it on every analysis because the references change all the time, but we do not want lots of temporary files.

Would it be possible to accept a FASTA file reference directly (for `-i` or a new option) and automatically index it, preferably keep in RAM only, or use temporary folder eg `/tmp` or `/dev/shm` for speed. And then delete the files at the end?

To be able to do this would make it much easier for bacterial genome analysis!
```
% MapCaller -ref reference.fasta -f R1.fq -f2 R2.fq ....
```

**Comment by hsinnan75** [comment]
Thanks for the suggestion. I'll add this feature to MapCaller.

**Comment by hsinnan75** [comment]
I've updated MapCaller to v0.9.9.28. It builds the bwt index files on the fly. The built index files will be removed after the job is done.

% MapCaller -r reference.fasta -f R1.fq -f2 R2.fq ....

**Comment by tseemann** [comment]
This is very helpful !
