### ISSUE TITLE
Does `-bam -` send the BAM to stdout ?

### ISSUE THREAD

**Issue by tseemann** [hsinnan75/MapCaller#52]
I was trying to send `-bam` to `stdout` using `/dev/stdout` but it failed, but `-` worked which was good. 

I could not find any documentation for this feature.

Does it work for `-output_vcf` and `-sam` too?

**Comment by hsinnan75** [comment]
MapCaller checks the output filename in case the output file cannot be created. Unfortunately, /dev/stdout and /dev/stderr are not accepted. I'll fix this problem.

**Comment by tseemann** [comment]
If `-` works (which it does?), then nothing needs to be done. `-` is a common practice in Unix for `stdin`.

Just add documentation about it :-)

**Comment by hsinnan75** [comment]
Hi, I've fixed the problem. Now MapCaller can output to /dev/stdout.

**Comment by tseemann** [comment]
Thank you.

Can you confirm that using `-` (hyphen or dash) as an output filename is _intended_ to go to `stdout` ?

**Comment by hsinnan75** [comment]
I've updated MapCaller to v0.9.9.29. It considers "-" as an output filename for stdout.
