### ISSUE TITLE
##reference=tmp_idx

### ISSUE THREAD

**Issue by tseemann** [hsinnan75/MapCaller#54]
When using the new `-r ref.fa` option, the VCF file has
```
##reference=tmp_idx
```
Can it please have the name of the reference files from `-r` instead?

**Comment by hsinnan75** [comment]
Thank you! I forgot to change that. It's been fixed.

**Comment by tseemann** [comment]
✅ https://github.com/hsinnan75/MapCaller/commit/5a15f05624e309e244f994cabcd32338f2e37280a
