### ISSUE TITLE
Gaps seem to be too big?

### ISSUE THREAD

**Issue by tseemann** [hsinnan75/MapCaller#56]
I got this VCF file:
```
##contig=<ID=ctg000001c,length=2880941>
ctg000001c      199338  .       A       <*>     0       DUP     END=2880941
ctg000001c      200045  .       A       <*>     0       Gaps    END=2880941
ctg000001c      200045  .       A       <*>     0       Gaps    END=2880941
ctg000001c      200226  .       A       <*>     0       DUP     END=2880941ctg000001c      282576  .       TT      T       19      PASS    RC=0;TYPE=del
<more results>
```
It seems to be saying there is a gap (unmapped reads) from 200 kbp to 2880 kbp (nearly the whole sequence). I know this is wrong, as the reads are from the same genome, and there are variants being called in the "Gaps" region. And the DUP regions also seem to go to the end of the sequence?

Is this a bug or am I misunderstanding?

PS. `MapCaller v0.9.9.33`

**Comment by hsinnan75** [comment]
@tseemann Thank you for reporting this bug. I'll fix it asap.

**Comment by hsinnan75** [comment]
I tried to fix this bug, but I was not sure if it works on your data. Please let me know if it happens again. It'd much better if I could test with your dataset. Thank you!
The latest version is v0.9.9.35.

**Comment by tseemann** [comment]
It does not work on my data.  
 I will try and send you my data.
I tried `-max_cnv 100000000` and it still reported them.

UPDATE: i have sent a link to your gmail to let you try the data

**Comment by hsinnan75** [comment]
I've fixed the bug. It happened because I did not capture the correct size of cnv and unmapped region. Please update MapCaller to v0.9.9.36. Thank you!

**Comment by hsinnan75** [comment]
I modified the rules for the identification of duplicated and unmapped regions. The previous rules were not complete. Please update MapCaller to v0.9.9.36. Thank you!

**Comment by tseemann** [comment]
Seems to be fixed
