### ISSUE TITLE
Wrong case in VCF file - REF vs Ref and missing q10

### ISSUE THREAD

**Issue by tseemann** [hsinnan75/MapCaller#64]
```
##FILTER=<ID=Ref,Description="Genotyping model thinks this site is reference.">
##FILTER=<ID=BreakPoint,Description="It is predicted as a breakpoint">
##FILTER=<ID=DUP,Description="Duplicated regions(>=50bp).">
```
1. In the VCF you use "REF" not "Ref"  

2. In the VCF you use "q10" but there is no q10 in VCF header above

```
[W::vcf_parse] FILTER 'REF' is not defined in the header
[W::vcf_parse] INFO 'DP' is not defined in the header, assuming Type=String
```

3. Missing defintion of DP ?

**Comment by hsinnan75** [comment]
Thank you for pointing our those issues, I'll fix them.

**Comment by hsinnan75** [comment]
I've fixed the REF and q10 in VCF header. And I also defined  INFO 'DP' in the header. Thank you for pointing out those issues.
