### ISSUE TITLE
Can you move to htslib 1.11 ?

### ISSUE THREAD

**Issue by tseemann** [hsinnan75/MapCaller#65]
COuld you move to newer htslib?
Or is it not important.
You bundle 1.5

**Comment by hsinnan75** [comment]
I modified some functions in htslib and MapCaller would use those modified functions. If I move to newer htslib, I have to modify them again whenever there are newer version. If it is okay, I'd like to stay the current version. It's been a while and I kind of forget what I have modified in htslib.

**Comment by tseemann** [comment]
"and I kind of forget what I have modified in htslib."  

I understand this problem well :-)

Recent htslib is much faster and 100s of bugs fixed.
