### ISSUE TITLE
Ability to use existing htslib ?

### ISSUE THREAD

**Issue by tseemann** [hsinnan75/MapCaller#7]
It would be great if you could support linking against `htslib` I have installed already, rather than compiling your own version.

This would make it easier to package MapCaller into brew and bioconda.

Could you add a flag to the makefile, eg `HTSLIB=/path/to/my/htslib` ?

**Comment by tseemann** [comment]
I have tested this (I have `libhts.so.2`) and it works:
```
main:           $(OBJECT)
                        $(Compiler) $(FLAGS) $(OBJECT) -o MapCaller $(LIB) -lhts -lbz2 -llzma
```

**Comment by hsinnan75** [comment]
I made some changes of htslib. Thus Mapcaller cannot use the original htslib. I'll try to fix this problem. Thank you.

**Comment by tseemann** [comment]
I compiled it with `htslib 1.9` installed on my system.   

What bugs will this cause?

**Comment by hsinnan75** [comment]
htslib is used for outputing BAM file. However, I modified the original htslib source codes to change the arguments for the functions of SamHdr2BamHdr and sam_hdr_write. If you used a different version of htslib and would like to output the BAM file, MapCaller might fail to complete the task. I'll try to fix or remove this function from MapCaller in the future.

**Comment by tseemann** [comment]
Ok I will make sure not to use external htslib! Thank you
